spring:
  application:
    name: 4iren-front
  # html,css 수정시 새로고침 안해도 바로 반영되는 코드
  thymeleaf:
    cache: false
  web:
    resources:
          cache:
            period: 0

  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 60000

logging:
  level:
    root: info

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  cookie:
    secure: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus