package com.nhnacademy.front.core.dto.team;

public enum TeamStatusCause {
    TEAM_CREATED,
    OWNER_REQUESTED_SUSPENSION,
    OWNER_REQUESTED_ACTIVATION,
    OWNER_ROLE_DOWNGRADED,
    OWNER_ROLE_RESTORED,
    ADMIN_SUSPENDED,
    OWNER_ARCHIVED,
    LEGACY_MIGRATION
}
